### PR TITLE
Private Events app 

### PR DESCRIPTION
**Pull request by janis-jenny**
Three models:

- User

- Event

- Attendance

Technologies used:

- Rails

- Bootstrap

- Capybara

- Rspec

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team. 💻 👀 ✨ 

- Great design and style. Good work there.
- Easy-to-use interface. Very clear and straightforward.

## However, there are some changes required 👀 🧰 🔨 🔧 

- When I use invalid values to sign-up,. the page doesn't really tell me what went wrong. Please add a proper error message here.
- When I use invalid input to create an event, the same problem happens. Please fix this as well.
- If I create an event that is happening in 1 day from today (tomorrow), the app classifies it as a "past event". Please fix this:
image
- When I create a new account, the app does not automatically log me in. Please make the user experience more comfortable by automatically logging-in after creating a new account.
- When I try to attend an event created by another user, the app classifies it as a "Created event" (an event created by me, instead of by the other user as it should be). Please fix this too: 
image

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @janis-jenny and @AlanSoto31   ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [x] Fix your rubocop errors. Most of them can be fixed by using `rubocop -a`.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi @AlanSoto31 and @janis-jenny! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] Your linters are not configured correctly which is why they are not showing up on your PR. Your folder is named incorrectly. Your folder should be `.github/workflows` and yours is named `.github/workflow` 
Screenshot from [microverse linters config](https://github.com/microverseinc/linters-config/tree/master/ror) 👇🏾 
Screen Shot 2021-01-07 at 4 26 44 PM
Screenshot from your GH Repo 👇🏾 
Screen Shot 2021-01-07 at 4 28 05 PM

- [ ] Your rubocop tests are failing. 👇🏾 
Screen Shot 2021-01-07 at 5 05 09 PM
  

- [ ] One of your rspec tests are failing 👇🏾 
Screen Shot 2021-01-07 at 5 06 08 PM



****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Review by ebeagusamuel — APPROVED** [review]
# Project Approved :100: 
### You have done well fixing the GitHub actions issues you had.
### The project is now approved and you can merge this branch and good luck with the next project.
slack(@ebeagusamuel)

**Pull request merged**
